# Generated by Django 4.2.23 on 2025-08-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('venue_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Event poster or promotional image', null=True, upload_to='events/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Ticket price (0.00 for free events)', max_digits=6)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='artists.artist')),
            ],
        ),
    ]
