# Generated by Django 4.2.23 on 2025-08-04 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(default='Our Story', max_length=200)),
                ('story_lead', models.TextField(help_text='Main paragraph for the story section')),
                ('story_content', models.TextField(help_text='Additional content for the story section')),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_content', models.TextField(help_text='Content for the mission section')),
                ('space_title', models.CharField(default='The Space', max_length=200)),
                ('space_content', models.TextField(help_text='Content for the space section')),
                ('programming_title', models.CharField(default='Programming & Production', max_length=200)),
                ('programming_content', models.TextField(help_text='Content for the programming section')),
                ('community_title', models.CharField(default='Community & Partnerships', max_length=200)),
                ('community_content', models.TextField(help_text='Content for the community section')),
                ('address', models.TextField(default='71 Bread St\nPenzance TR18 2EQ')),
                ('opening_hours', models.TextField(default='Monday – Thursday: 5pm – 12am\nFriday & Saturday: 5pm - 3am\nSunday: 3pm - 11pm')),
                ('email', models.EmailField(default='info@studiobar.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
