# Generated by Django 4.2.23 on 2025-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Event poster or promotional image', null=True, upload_to='events/'),
        ),
    ]
