# Generated by Django 4.2.23 on 2025-08-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ticket price (0.00 for free events)', max_digits=6),
        ),
    ]
