# Generated by Django 4.2.23 on 2025-08-06 09:43

from django.db import migrations


def copy_artists_data(apps, schema_editor):
    # Get the old and new Artist models
    OldArtist = apps.get_model('index', 'Artist')
    NewArtist = apps.get_model('artists', 'Artist')
    
    # Copy all artists from old table to new table
    for artist in OldArtist.objects.all():
        NewArtist.objects.create(
            id=artist.id,
            name=artist.name,
            genre=artist.genre,
            bio=artist.bio,
            social_links=artist.social_links
        )


def reverse_copy_artists_data(apps, schema_editor):
    # Delete all artists from new table
    NewArtist = apps.get_model('artists', 'Artist')
    NewArtist.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_event_price'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_artists_data, reverse_copy_artists_data),
    ]
