# Generated by Django 4.2.23 on 2025-08-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('index', '0004_auto_20250806_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='artists.artist'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
