# Generated by Django 4.2.23 on 2025-08-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_event_artist_delete_artist'),
        ('index', '0004_auto_20250806_0947'),
    ]

    operations = [
    ]
