# Generated by Django 4.2.23 on 2025-08-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_merge_20250806_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
